### ISSUE TITLE
Compile error with g++ 4.7

### ISSUE THREAD

**Issue by emdeesee** [Andersbakken/rct#42]
/rct/rct/EventLoop.cpp:93:32: error: 'this' was not captured for this lambda function
CMakeFiles/rct.dir/build.make:215: recipe for target 'CMakeFiles/rct.dir/rct/EventLoop.cpp.o' failed
make[2]: *** [CMakeFiles/rct.dir/rct/EventLoop.cpp.o] Error 1

**Comment by cslux** [comment]
Oops. I got the same error at work on a Debian Wheezy server (gcc 4.7). But I have compiled clang and gcc manually now and I completely forgot about it.

**Comment by cslux** [comment]
@emdeesee 

Thanks for reporting.

Christian
